source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'Segment-UrbanAirship_Example' do
  pod 'Segment-UrbanAirship',:path => ".."
end

target 'Segment-UrbanAirship_Tests' do
  pod 'Segment-UrbanAirship',:path => ".."
  pod 'OCMock'
end
